#!/usr/bin/env python3
"""Find the best hole-squeeze axis through an arbitrary link.

The hole-squeeze's topology guarantee holds about ANY line the link avoids --
symmetry never enters the proof, it only tells you where the axis is for free.
For an irregular structure the axis has to be found, and "best" is not just
"widest empty tunnel": an axis the curve merely runs parallel to has clearance
but no leverage, because the squeeze only shortens the AZIMUTHAL part of the
curve. So candidates are generated by clearance and ranked by the length they
would actually remove.

Method:
  1. densify the curve so distances are to the curve, not to sparse vertices
  2. sweep directions on a Fibonacci sphere; for each, project the curve onto
     the perpendicular plane and solve the largest-empty-circle problem
     (Voronoi vertices restricted to the Delaunay hull of the projection)
  3. take the top candidates by clearance and, for each, apply the actual
     squeeze map to the polyline at a probe factor and measure the length
     removed; return the axis that removes the most

Measured validation: on a trapped 4-component link (rop 247.22, no symmetry,
the guide's 4_LC after 50k steps) this found a tunnel of wall radius 2.95 D at
axis (0.743, 0.035, -0.669), offset 0.07 from the centroid, through which a
f=0.20 squeeze removes 30.0% of the curve length while staying strut-limited
(margin 1.15) -- a stronger scan than the symmetric 5-component case that
produced a 6.5-unit record. On Cn-symmetric structures it recovers the
symmetry axis on its own.

Usage:
    python3 find_axis.py file.xyz [--dirs 160] [--probe 0.5] [--blend 0.5]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from scipy.spatial import Voronoi, Delaunay, cKDTree

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from tighten_link_xyz import read_xyz  # noqa: E402


def _densify(comps, step):
    out = []
    for c in comps:
        V = np.vstack([c, c[:1]])
        for a, b in zip(V[:-1], V[1:]):
            n = max(2, int(np.linalg.norm(b - a) / step))
            out.append(a + np.outer(np.linspace(0, 1, n, endpoint=False), b - a))
    return np.vstack(out)


def _fib_sphere(n):
    i = np.arange(n) + 0.5
    phi = np.arccos(1 - 2 * i / n)
    th = np.pi * (1 + 5 ** 0.5) * i
    return np.column_stack([np.sin(phi) * np.cos(th),
                            np.sin(phi) * np.sin(th), np.cos(phi)])


def _length(comps):
    return sum(float(np.linalg.norm(
        np.diff(np.vstack([c, c[:1]]), axis=0), axis=1).sum()) for c in comps)


def find_axis(comps, ndirs=160, step=0.05, top_k=8, probe=0.5, blend=0.5):
    """Returns (axis, point, clearance, removed_fraction) for the best axis.

    axis: unit direction; point: a 3-D point the axis passes through;
    clearance: distance from the axis to the nearest point of the CURVE
    (subtract tau for the tunnel wall radius); removed_fraction: fraction of
    curve length the squeeze at the probe factor would remove about this axis.
    """
    from radial_squeeze import apply_squeeze_about

    comps = [np.asarray(c, float) for c in comps]
    O = np.vstack(comps).mean(axis=0)
    comps0 = [c - O for c in comps]
    D = _densify(comps0, step)
    tree = cKDTree(D)
    L0 = _length(comps0)

    cands = []
    for ax in _fib_sphere(ndirs):
        tmp = np.array([1.0, 0, 0]) if abs(ax[0]) < 0.9 else np.array([0, 1.0, 0])
        e1 = np.cross(ax, tmp); e1 /= np.linalg.norm(e1)
        e2 = np.cross(ax, e1)
        Q = np.column_stack([D @ e1, D @ e2])
        try:
            vor = Voronoi(Q[::3])
            tri = Delaunay(Q[::7])
            inside = tri.find_simplex(vor.vertices) >= 0
            centres = vor.vertices[inside]
            if not len(centres):
                continue
            d, _ = cKDTree(Q).query(centres)
            k = int(np.argmax(d))
            cands.append((float(d[k]), ax.copy(),
                          centres[k][0] * e1 + centres[k][1] * e2))
        except Exception:
            continue
    if not cands:
        return None
    cands.sort(key=lambda t: -t[0])

    best = None
    for clear, ax, pt in cands[:top_k]:
        sq = apply_squeeze_about(comps0, pt, ax, probe, blend)
        removed = (L0 - _length(sq)) / L0
        if best is None or removed > best[3]:
            best = (ax, pt + O, clear, removed)
    return best


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", type=Path)
    ap.add_argument("--dirs", type=int, default=160)
    ap.add_argument("--probe", type=float, default=0.5)
    ap.add_argument("--blend", type=float, default=0.5)
    a = ap.parse_args()
    comps = [np.asarray(c, float) for c in read_xyz(a.input)]
    r = find_axis(comps, ndirs=a.dirs, probe=a.probe, blend=a.blend)
    if r is None:
        print("no axis found"); return 1
    ax, pt, clear, rem = r
    print(f"axis      ({ax[0]:+.4f}, {ax[1]:+.4f}, {ax[2]:+.4f})")
    print(f"point     ({pt[0]:+.4f}, {pt[1]:+.4f}, {pt[2]:+.4f})")
    print(f"clearance {clear:.4f}  (wall radius = clearance - tau)")
    print(f"removes   {rem*100:.1f}% of length at probe factor {a.probe}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
